### ISSUE TITLE
XMIR output doesn't use `xmlns`

### ISSUE THREAD

**Issue by yegor256** [objectionary/phino#126]
The top level `<object>` element misses this:

```
<object xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        dob="2025-04-24T11:14:36"
        ms="0"
        revision="c577c6b"
        time="2025-06-23T01:45:02.070017335Z"
        version="0.10.0"
        xsi:noNamespaceSchemaLocation="https://www.eolang.org/xsd/XMIR-0.56.0.xsd">
```

All these attributes are important and must be present, in order to be XSD-valid XMIR.

**Comment by yegor256** [comment]
@maxonfjvipon FYI

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#131](https://github.com/objectionary/phino/issues/131) is still not solved.

**Comment by maxonfjvipon** [comment]
@yegor256 fixed in new release

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#157](https://github.com/objectionary/phino/issues/157) is still not solved; solved: [#131](https://github.com/objectionary/phino/issues/131).

**Comment by 0pdd** [comment]
@yegor256 all 2 puzzles are solved here: [#131](https://github.com/objectionary/phino/issues/131), [#157](https://github.com/objectionary/phino/issues/157).
